inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - Guardfile
    - Gemfile
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/Debugger:
  Enabled: false

Style/Semicolon:
  Enabled: false
