inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'Guardfile'
    - 'Gemfile'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
